# 📝 Advanced NumPy — Assignment

**Instructions**

- Solve every question using NumPy only — no Python `for` loops unless a question explicitly allows one.
- Where a question asks you to predict something first, write the prediction as a comment before running the code.
- Print the shape of your result whenever an answer involves reshaping, stacking or matrix multiplication.
- Searching the documentation is allowed and encouraged.

In [8]:
import numpy as np


### Q1.

A class has 4 students and 3 subjects. Their marks are given below. The examiner announces a subject-wise bonus of 5, 2 and 8 marks respectively. Add the bonus to every student in one line using broadcasting, then cap any mark above 100 back to 100 and report how many marks had to be capped.

```python
marks = np.array([[88, 96, 95],
                  [72, 99, 91],
                  [98, 85, 97],
                  [60, 75, 80]])
```

In [9]:
# Q1
marks = np.array([[88, 96, 95],
                  [72, 99, 91],
                  [98, 85, 97],
                  [60, 75, 80]])

new_marks = marks + np.array([5, 2, 8])
print(new_marks)

capped = (new_marks > 100).sum()
new_marks = np.minimum(new_marks, 100)
print(new_marks)
print("marks capped:", capped)

[[ 93  98 103]
 [ 77 101  99]
 [103  87 105]
 [ 65  77  88]]
[[ 93  98 100]
 [ 77 100  99]
 [100  87 100]
 [ 65  77  88]]
marks capped: 4


### Q2.

Create a 5x5 matrix with a border of 1s and 0s inside, without writing the matrix out by hand.

In [10]:
# Q2
border = np.ones((5, 5), dtype=int)
border[1:-1, 1:-1] = 0
print(border)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


### Q3.

Without running the code, predict the shape of `np.arange(30).reshape(5, -1).T`. Write your prediction as a comment, then verify it. Also explain in a comment why `np.arange(30).reshape(4, -1)` fails.

In [11]:
# Q3
# prediction: reshape(5, -1) gives (5, 6), and .T flips it to (6, 5)
x = np.arange(30).reshape(5, -1).T
print(x.shape)

# np.arange(30).reshape(4, -1) fails because 30 / 4 = 7.5,
# numpy cannot make rows with half an element, so the -1 cannot be worked out

(6, 5)


### Q4.

Two arrays of size 4 are given. First join them with `hstack` and print the shape. Then, using the same two arrays, build a proper (4, 2) two-column table. In a comment, state why the first attempt did not produce two columns.

```python
heights = np.array([172, 158, 181, 166])
weights = np.array([68, 52, 84, 59])
```

In [12]:
# Q4
heights = np.array([172, 158, 181, 166])
weights = np.array([68, 52, 84, 59])

joined = np.hstack((heights, weights))
print(joined, joined.shape)

table = np.hstack((heights.reshape(-1, 1), weights.reshape(-1, 1)))
print(table)
print(table.shape)

# first attempt: both arrays are 1D, so hstack just puts them one after
# another in a single long row of 8. To get columns they must be (4, 1) first.

[172 158 181 166  68  52  84  59] (8,)
[[172  68]
 [158  52]
 [181  84]
 [166  59]]
(4, 2)


### Q5.

Given a 1D array of 12 monthly sales figures, reshape it into 4 quarters of 3 months each and find which quarter (index) had the highest average sales, along with that average.

```python
sales = np.array([120, 135, 98, 160, 175, 190, 88, 92, 105, 210, 198, 230])
```

In [13]:
# Q5
sales = np.array([120, 135, 98, 160, 175, 190, 88, 92, 105, 210, 198, 230])

quarters = sales.reshape(4, 3)
print(quarters, quarters.shape)

avg = quarters.mean(axis=1)
print("quarter averages:", avg.round(2))
print("best quarter index:", avg.argmax())
print("its average:", avg.max().round(2))

[[120 135  98]
 [160 175 190]
 [ 88  92 105]
 [210 198 230]] (4, 3)
quarter averages: [117.67 175.    95.   212.67]
best quarter index: 3
its average: 212.67


### Q6.

Build a 3x3 multiplication table from the array below using broadcasting only. Do not use loops and do not use `np.outer` — reshape one of the operands so that broadcasting produces the grid.

```python
a = np.array([2, 3, 4])
```

In [14]:
# Q6
a = np.array([2, 3, 4])

table = a.reshape(3, 1) * a
print(table)
print(table.shape)

[[ 4  6  8]
 [ 6  9 12]
 [ 8 12 16]]
(3, 3)


### Q7.

Create an array of numbers from 1 to 20 and replace every multiple of 3 with -1.

In [15]:
# Q7
arr = np.arange(1, 21)
arr[arr % 3 == 0] = -1
print(arr)

[ 1  2 -1  4  5 -1  7  8 -1 10 11 -1 13 14 -1 16 17 -1 19 20]


### Q8.

For the matrix below, scale every column into the 0 to 1 range using column-wise min-max normalization `(x - col_min) / (col_max - col_min)`. Use broadcasting only — no loops. Verify that each column of the result has a minimum of 0 and a maximum of 1.

```python
X = np.array([[ 50, 1200,  3],
              [ 80, 1500,  9],
              [ 65,  900,  5],
              [ 95, 2000,  7]])
```

In [16]:
# Q8
X = np.array([[ 50, 1200,  3],
              [ 80, 1500,  9],
              [ 65,  900,  5],
              [ 95, 2000,  7]])

col_min = X.min(axis=0)
col_max = X.max(axis=0)
scaled = (X - col_min) / (col_max - col_min)
print(scaled.round(3))

print("min of each column:", scaled.min(axis=0))
print("max of each column:", scaled.max(axis=0))

[[0.    0.273 0.   ]
 [0.667 0.545 1.   ]
 [0.333 0.    0.333]
 [1.    1.    0.667]]
min of each column: [0. 0. 0.]
max of each column: [1. 1. 1.]


### Q9.

Award medals to the scores below using nested `np.where`: 'Gold' for 90 and above, 'Silver' for 75 and above, 'Bronze' for 60 and above, and 'None' otherwise. Then count how many students received each medal.

```python
scores = np.array([94, 61, 77, 45, 90, 88, 59, 72])
```

In [17]:
# Q9
scores = np.array([94, 61, 77, 45, 90, 88, 59, 72])

medals = np.where(scores >= 90, 'Gold',
         np.where(scores >= 75, 'Silver',
         np.where(scores >= 60, 'Bronze', 'None')))
print(medals)

names, counts = np.unique(medals, return_counts=True)
print(names)
print(counts)

['Gold' 'Bronze' 'Silver' 'None' 'Gold' 'Silver' 'None' 'Bronze']
['Bronze' 'Gold' 'None' 'Silver']
[2 2 2 2]


### Q10.

Given the matrix below, use `np.where` with a single condition to obtain the row and column indices of every element greater than 50, print those elements, and then replace them with 0 in a copy of the matrix while leaving the original untouched.

```python
m = np.array([[10, 80, 45],
              [55, 20, 99],
              [70, 33, 12]])
```

In [18]:
# Q10
m = np.array([[10, 80, 45],
              [55, 20, 99],
              [70, 33, 12]])

rows, cols = np.where(m > 50)
print("rows:", rows)
print("cols:", cols)
print("values:", m[rows, cols])

m_copy = m.copy()
m_copy[rows, cols] = 0
print(m_copy)
print(m)   # original is still the same

rows: [0 1 1 2]
cols: [1 0 2 0]
values: [80 55 99 70]
[[10  0 45]
 [ 0 20  0]
 [ 0 33 12]]
[[10 80 45]
 [55 20 99]
 [70 33 12]]


### Q11.

Three sensors each recorded 5 readings. Stack them so that each sensor becomes a row, and separately stack them so that each sensor becomes a column. Print both shapes and confirm that one is the transpose of the other.

```python
s1 = np.array([12, 15, 11, 19, 14])
s2 = np.array([22, 18, 25, 21, 20])
s3 = np.array([31, 35, 29, 33, 30])
```

In [19]:
# Q11
s1 = np.array([12, 15, 11, 19, 14])
s2 = np.array([22, 18, 25, 21, 20])
s3 = np.array([31, 35, 29, 33, 30])

as_rows = np.vstack((s1, s2, s3))
as_cols = np.column_stack((s1, s2, s3))
print(as_rows.shape)
print(as_cols.shape)

print(np.array_equal(as_rows.T, as_cols))

(3, 5)
(5, 3)
True


### Q12.

Create a random 6x6 matrix with `seed = 1` and values between 1 and 100, then find the row-wise maximum and the column-wise minimum.

In [20]:
# Q12
np.random.seed(1)
mat = np.random.randint(1, 101, (6, 6))
print(mat)

print("row-wise max:", mat.max(axis=1))
print("column-wise min:", mat.min(axis=0))

[[38 13 73 10 76  6]
 [80 65 17  2 77 72]
 [ 7 26 51 21 19 85]
 [12 29 30 15 51 69]
 [88 88 95 97 87 14]
 [10  8 64 62 23 58]]
row-wise max: [76 80 85 69 97 64]
column-wise min: [ 7  8 17  2 19  6]


### Q13.

A and B are both 2x3 matrices. Compute `A @ B.T` and `A.T @ B`. Print the shape of each result and explain in a comment why both multiplications are legal while `A @ B` is not.

```python
A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([[7, 8, 9],
              [1, 0, 2]])
```

In [21]:
# Q13
A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([[7, 8, 9],
              [1, 0, 2]])

r1 = A @ B.T
r2 = A.T @ B
print(r1, r1.shape)
print(r2, r2.shape)

# for A @ B the columns of A must equal the rows of B.
# A @ B.T  -> (2,3) @ (3,2) -> inner 3 and 3 match -> (2,2)
# A.T @ B  -> (3,2) @ (2,3) -> inner 2 and 2 match -> (3,3)
# A @ B    -> (2,3) @ (2,3) -> inner 3 and 2 do not match, so it gives an error

[[ 50   7]
 [122  16]] (2, 2)
[[11  8 17]
 [19 16 28]
 [27 24 39]] (3, 3)


### Q14.

Build a complete multi-step pipeline. Starting from the two arrays below: convert them into column vectors, join them into a single two-column table, attach a third column holding each row's total, then multiply the three-column table by `w = [0.5, 0.2, 0.3]` to obtain one score per row. Finally use `np.where` to mark each score as 1 if it is above the average score and 0 otherwise. Report the shape of every intermediate array.

```python
hours = np.array([2, 8, 5, 10, 3, 7])
attendance = np.array([55, 92, 70, 98, 60, 85])
```

In [22]:
# Q14
hours = np.array([2, 8, 5, 10, 3, 7])
attendance = np.array([55, 92, 70, 98, 60, 85])

h = hours.reshape(-1, 1)
a = attendance.reshape(-1, 1)
print("column vectors:", h.shape, a.shape)

table = np.hstack((h, a))
print("two column table:", table.shape)

total = table.sum(axis=1).reshape(-1, 1)
table = np.hstack((table, total))
print("with total column:", table.shape)
print(table)

w = np.array([0.5, 0.2, 0.3])
score = table @ w
print("scores:", score, score.shape)

result = np.where(score > score.mean(), 1, 0)
print("average score:", score.mean())
print("above average:", result, result.shape)

column vectors: (6, 1) (6, 1)
two column table: (6, 2)
with total column: (6, 3)
[[  2  55  57]
 [  8  92 100]
 [  5  70  75]
 [ 10  98 108]
 [  3  60  63]
 [  7  85  92]]
scores: [29.1 52.4 39.  57.  32.4 48.1] (6,)
average score: 43.0
above average: [0 1 0 1 0 1] (6,)


### Q15.

Apply min-max normalization to scale any array into the 0 to 1 range using `(x - min) / (max - min)`.

In [23]:
# Q15
def min_max(arr):
    return (arr - arr.min()) / (arr.max() - arr.min())

data = np.array([12, 45, 7, 30, 60, 22])
print(min_max(data).round(3))

[0.094 0.717 0.    0.434 1.    0.283]


### Q16.

Take the array below and create two 1D versions of it — one with `flatten()` and one with `ravel()`. Change the first element of each, then print the original matrix. Explain the difference you observe in a comment.

```python
m = np.array([[4, 8, 15],
              [16, 23, 42]])
```

In [24]:
# Q16
m = np.array([[4, 8, 15],
              [16, 23, 42]])

f = m.flatten()
r = m.ravel()

f[0] = 100
print(m)

r[0] = 100
print(m)

# flatten() always makes a new copy, so changing f did not touch m.
# ravel() returns a view when it can, it shares memory with m,
# so changing r also changed m.

[[ 4  8 15]
 [16 23 42]]
[[100   8  15]
 [ 16  23  42]]


### Q17.

28 daily temperature readings are given. Reshape them into 4 weeks of 7 days, then: find each week's average, identify the hottest week, and count how many individual days crossed 35 degrees.

```python
np.random.seed(7)
temps = np.random.randint(15, 41, 28)
```

In [25]:
# Q17
np.random.seed(7)
temps = np.random.randint(15, 41, 28)

weeks = temps.reshape(4, 7)
print(weeks, weeks.shape)

week_avg = weeks.mean(axis=1)
print("weekly average:", week_avg.round(2))
print("hottest week index:", week_avg.argmax())
print("days above 35:", (temps > 35).sum())

[[30 19 40 37 18 34 38]
 [22 40 29 38 23 40 29]
 [25 23 22 21 19 31 22]
 [27 15 26 38 21 34 27]] (4, 7)
weekly average: [30.86 31.57 23.29 26.86]
hottest week index: 1
days above 35: 7


### Q18.

Create two random 3x3 matrices A and B, compute `A @ B` and `B @ A`, and check whether the two results are equal. State your conclusion about matrix multiplication in a comment.

In [26]:
# Q18
np.random.seed(0)
A = np.random.randint(1, 10, (3, 3))
B = np.random.randint(1, 10, (3, 3))

AB = A @ B
BA = B @ A
print(AB)
print(BA)
print("equal?", np.array_equal(AB, BA))

# matrix multiplication is not commutative, A @ B is generally not equal to B @ A

[[ 89  76  97]
 [136  76 128]
 [115  88 120]]
[[130  91 105]
 [104  46  79]
 [134  99 109]]
equal? False


### Q19.

Given the marks matrix below (5 students x 4 subjects), first replace every mark below 35 with 35, then compute each student's total, and finally print the index of the topper along with their total.

```python
marks = np.array([[45, 28, 67, 80],
                  [33, 90, 55, 41],
                  [72, 66, 30, 58],
                  [88, 79, 91, 84],
                  [25, 40, 38, 52]])
```

In [27]:
# Q19
marks = np.array([[45, 28, 67, 80],
                  [33, 90, 55, 41],
                  [72, 66, 30, 58],
                  [88, 79, 91, 84],
                  [25, 40, 38, 52]])

marks = np.where(marks < 35, 35, marks)
print(marks)

totals = marks.sum(axis=1)
print("totals:", totals)
print("topper index:", totals.argmax(), "total:", totals.max())

[[45 35 67 80]
 [35 90 55 41]
 [72 66 35 58]
 [88 79 91 84]
 [35 40 38 52]]
totals: [227 221 231 342 165]
topper index: 3 total: 342


### Q20.

Start from `arr = np.arange(1, 11)`. Create one variable using a plain slice `arr[2:6]` and another using `arr[2:6].copy()`. Change the first element of each to 999, then print the original array and explain in a comment which change survived and why.

In [28]:
# Q20
arr = np.arange(1, 11)

view = arr[2:6]
copy = arr[2:6].copy()

view[0] = 999
copy[0] = 999
print(arr)

# the change made through `view` survived. A plain slice is a view of the
# same memory, so editing it edits arr. The .copy() has its own memory,
# so that 999 never reaches arr.

[  1   2 999   4   5   6   7   8   9  10]


### Q21.

Explore `np.diag` in the NumPy documentation and use it to extract the diagonal of a 4x4 matrix. Then use the same function in its second role — to build a diagonal matrix from a 1D array.

In [29]:
# Q21
mat = np.arange(1, 17).reshape(4, 4)
print(mat)
print("diagonal:", np.diag(mat))

d = np.diag([5, 10, 15, 20])
print(d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
diagonal: [ 1  6 11 16]
[[ 5  0  0  0]
 [ 0 10  0  0]
 [ 0  0 15  0]
 [ 0  0  0 20]]


---

**Before you submit:** re-run the notebook from top to bottom and make sure every cell executes without errors.