In [13]:
import numpy as np;

In [14]:
## learn about numpy


In [15]:
#creating a array from list 
arr_1d=np.array([34,34,3,43,3,5,34,3,43,443,3,4,34,3])
print("1D Array",arr_1d)

arr_2d=np.array([[343,3,43,4,34,34,3,34],[343,78,54,7,3,543,3454,4]])
print(arr_2d)

1D Array [ 34  34   3  43   3   5  34   3  43 443   3   4  34   3]
[[ 343    3   43    4   34   34    3   34]
 [ 343   78   54    7    3  543 3454    4]]


### List vs numpy array


In [20]:
py_list=[43,3453,343] #element wise multiplication 
print("python list multiplication",py_list*34)

np_array=np.array([34,3,53,3,4,34,3])
print("python array multiplication" , np_array * 2)

import time
start =time.time()
py_list=[i*2 for i in range(1000000)]
print("\n List operation time: ",time.time()-start)


start = time.time()
np_array=np.arange(1000000)*2
print("\n numpy  operation time: ",time.time()-start)


python list multiplication [43, 3453, 343, 43, 3453, 343, 43, 3453, 343, 43, 3453, 343, 43, 3453, 343, 43, 3453, 343, 43, 3453, 343, 43, 3453, 343, 43, 3453, 343, 43, 3453, 343, 43, 3453, 343, 43, 3453, 343, 43, 3453, 343, 43, 3453, 343, 43, 3453, 343, 43, 3453, 343, 43, 3453, 343, 43, 3453, 343, 43, 3453, 343, 43, 3453, 343, 43, 3453, 343, 43, 3453, 343, 43, 3453, 343, 43, 3453, 343, 43, 3453, 343, 43, 3453, 343, 43, 3453, 343, 43, 3453, 343, 43, 3453, 343, 43, 3453, 343, 43, 3453, 343, 43, 3453, 343, 43, 3453, 343, 43, 3453, 343]
python array multiplication [ 68   6 106   6   8  68   6]

 List operation time:  0.01959705352783203

 numpy  operation time:  0.007097005844116211


In [33]:
### creating array form scratch

zeros=np.zeros((3,4))
print("zeros array :\n",zeros)

ones=np.ones((2,3))
print("one  array:\n",ones)

full=np.full((2,2),9)
print("full array:\n",full)

random=np.random.random((2,3))
print("random array:\n",random)

sequence=np.arange(0,10,3)
print("sequence array:\n",sequence)



zeros array :
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
one  array:
 [[1. 1. 1.]
 [1. 1. 1.]]
full array:
 [[9 9]
 [9 9]]
random array:
 [[0.89632434 0.62205521 0.99657685]
 [0.43533089 0.92046881 0.60157087]]
sequence array:
 [0 3 6 9]


### vector , Matrix, Tensor

In [37]:
vector=np.array([343,35,3,53,4,34,3,34,3,43,4,3])
print("Vector :",vector)


matrix=np.array([[1,2,3],[4,5,6]])
print("Matrix:", matrix)


tensor=np.array([[[1,2],[3,4]],
                [[5,6],[7,8]]])
print("tensor:",tensor)

Vector : [343  35   3  53   4  34   3  34   3  43   4   3]
Matrix: [[1 2 3]
 [4 5 6]]
tensor: [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### array properties 

In [39]:
array=np.array([[1,2,3],[4,5,6]])
print("shape :",array.shape)
print("dimention:",array.ndim)
print("Size :",array.size)
print("Dtype:", array.dtype)

shape : (2, 3)
dimention: 2
Size : 6
Dtype: int64


In [ ]:
### Array reshaping 


In [47]:
array=np.array([232,34,3,43])
print(array)

array=np.arange(12)
print(array)

reshaped=array.reshape((3,4))
print(reshaped)

flattend=reshaped.flatten()
print(flattend)

# return view instead of copying 
raveled=reshaped.ravel()
print(raveled)

# transpose
transpose=reshaped.T
print(transpose)

[232  34   3  43]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


## numpy array operation 

In [50]:
array=np.array([1,2,3,4,5,6,7,8,9])
print(array)

print("Basic slicing :", array[2:7])
print("With steps:",array[2:9:2])
print("negative indexing:",array[-2])


[1 2 3 4 5 6 7 8 9]
Basic slicing : [3 4 5 6 7]
With steps: [3 5 7 9]
negative indexing: 8
